# Site settings
title: Coinkä¸¨Do Boom!
header-img: img/home-bg.jpg
email: coinkwang@163.com
description: 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://coink.wang" # the base hostname & protocol for your site


# Build settings
markdown: kramdown
paginate: 10

# SNS settings
RSS: false
weibo_username: 
zhihu_username:
facebook_username: 
twitter_username: 
github_username:  CoinkWang

sidebar: true                     
sidebar-about-description: ""
sidebar-avatar: /img/avatar.jpg

gems: [jekyll-paginate]