title: Coink | DO BOOM!
copyright_time: 2015-2025
author:
  name: CoinkWang
  email: cn.coink.wang@gmail.com
description: > # this means to ignore newlines until "show_subtitle:"
  Coink's Blog

show_subtitle: true

header_pages:
  - about.md
  - links.md

permalink: /:title.html

# date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
glance:
  date_format: "%Y-%m-%d"

# Build settings
# theme: glance

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-paginate

# 添加分页配置
paginate: 5  # 每页显示的文章数量
paginate_path: "/page/:num/"  # 分页URL路径格式 
